# Lab | Data Cleaning and Formatting

In this lab, we will be working with the customer data from an insurance company, which can be found in the CSV file located at the following link: https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv

# Challenge 1: Data Cleaning and Formatting

## Exercise 1: Cleaning Column Names

To ensure consistency and ease of use, standardize the column names of the dataframe. Start by taking a first look at the dataframe and identifying any column names that need to be modified. Use appropriate naming conventions and make sure that column names are descriptive and informative.

*Hint*:
- *Column names should be in lower case*
- *White spaces in column names should be replaced by `_`*
- *`st` could be replaced for `state`*

In [11]:
import pandas as pd

url = "https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv"

df = pd.read_csv(url)

print(df.head())

df.columns = (
    df.columns
    .str.lower()
    .str.strip()
    .str.replace(" ", "_")
)

df = df.rename(columns={"st": "state"})

print(df.columns)

  Customer          ST GENDER             Education Customer Lifetime Value  \
0  RB50392  Washington    NaN                Master                     NaN
1  QZ44356     Arizona      F              Bachelor              697953.59%
2  AI49188      Nevada      F              Bachelor             1288743.17%
3  WW63253  California      M              Bachelor              764586.18%
4  GA49547  Washington      M  High School or Below              536307.65%

    Income  Monthly Premium Auto Number of Open Complaints     Policy Type  \
0      0.0                1000.0                    1/0/00   Personal Auto
1      0.0                  94.0                    1/0/00   Personal Auto
2  48767.0                 108.0                    1/0/00   Personal Auto
3      0.0                 106.0                    1/0/00  Corporate Auto
4  36357.0                  68.0                    1/0/00   Personal Auto

   Vehicle Class  Total Claim Amount
0  Four-Door Car            2.704934
1  Four-Door Car         1131.464935
2   Two-Door Car          566.472247
3            SUV          529.881344
4  Four-Door Car           17.269323
Index(['customer', 'state', 'gender', 'education', 'customer_lifetime_value',
       'income', 'monthly_premium_auto', 'number_of_open_complaints',
       'policy_type', 'vehicle_class', 'total_claim_amount'],
      dtype='object')

## Exercise 2: Cleaning invalid Values

The dataset contains columns with inconsistent and incorrect values that could affect the accuracy of our analysis. Therefore, we need to clean these columns to ensure that they only contain valid data.

Note that this exercise will focus only on cleaning inconsistent values and will not involve handling null values (NaN or None).

*Hint*:
- *Gender column contains various inconsistent values such as "F", "M", "Femal", "Male", "female", which need to be standardized, for example, to "M" and "F".*
- *State abbreviations be can replaced with its full name, for example "AZ": "Arizona", "Cali": "California", "WA": "Washington"*
- *In education, "Bachelors" could be replaced by "Bachelor"*
- *In Customer Lifetime Value, delete the `%` character*
- *In vehicle class, "Sports Car", "Luxury SUV" and "Luxury Car" could be replaced by "Luxury"*

In [12]:

# Gender
df["gender"] = df["gender"].replace({
    "F": "F",
    "female": "F",
    "Femal": "F",
    "M": "M",
    "Male": "M"
})

# State
df["state"] = df["state"].replace({
    "AZ": "Arizona",
    "Cali": "California",
    "WA": "Washington"
})

# Education
df["education"] = df["education"].replace({
    "Bachelors": "Bachelor"
})

# Customer Lifetime Value
df["customer_lifetime_value"] = (
    df["customer_lifetime_value"]
    .str.replace("%", "", regex=False)
)

# Vehicle Class
df["vehicle_class"] = df["vehicle_class"].replace({
    "Sports Car": "Luxury",
    "Luxury SUV": "Luxury",
    "Luxury Car": "Luxury"
})

print(df["gender"].unique())
print(df["state"].unique())
print(df["education"].unique())
print(df["vehicle_class"].unique())

df.head()

[nan 'F' 'M']
['Washington' 'Arizona' 'Nevada' 'California' 'Oregon' nan]
['Master' 'Bachelor' 'High School or Below' 'College' 'Doctor' nan]
['Four-Door Car' 'Two-Door Car' 'SUV' 'Luxury' nan]

,customer,state,gender,education,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,policy_type,vehicle_class,total_claim_amount
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,1/0/00,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,F,Bachelor,697953.59,0.0,94.0,1/0/00,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1288743.17,48767.0,108.0,1/0/00,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,M,Bachelor,764586.18,0.0,106.0,1/0/00,Corporate Auto,SUV,529.881344
4,GA49547,Washington,M,High School or Below,536307.65,36357.0,68.0,1/0/00,Personal Auto,Four-Door Car,17.269323

## Exercise 3: Formatting data types

The data types of many columns in the dataset appear to be incorrect. This could impact the accuracy of our analysis. To ensure accurate analysis, we need to correct the data types of these columns. Please update the data types of the columns as appropriate.

It is important to note that this exercise does not involve handling null values (NaN or None).

*Hint*:
- *Customer lifetime value should be numeric*
- *Number of open complaints has an incorrect format. Look at the different values it takes with `unique()` and take the middle value. As an example, 1/5/00 should be 5. Number of open complaints is a string - remember you can use `split()` to deal with it and take the number you need. Finally, since it should be numeric, cast the column to be in its proper type.*

In [13]:
df["customer_lifetime_value"] = pd.to_numeric(
    df["customer_lifetime_value"],
    errors="coerce"
)

print(df["number_of_open_complaints"].unique())

df["number_of_open_complaints"] = (
    df["number_of_open_complaints"]
    .str.split("/")
    .str[1]
)

df["number_of_open_complaints"] = pd.to_numeric(
    df["number_of_open_complaints"],
    errors="coerce"
)

print(df.dtypes)

['1/0/00' '1/2/00' '1/1/00' '1/3/00' '1/5/00' '1/4/00' nan]
customer                      object
state                         object
gender                        object
education                     object
customer_lifetime_value      float64
income                       float64
monthly_premium_auto         float64
number_of_open_complaints    float64
policy_type                   object
vehicle_class                 object
total_claim_amount           float64
dtype: object

## Exercise 4: Dealing with Null values

Identify any columns with null or missing values. Identify how many null values each column has. You can use the `isnull()` function in pandas to find columns with null values.

Decide on a strategy for handling the null values. There are several options, including:

- Drop the rows or columns with null values
- Fill the null values with a specific value (such as the column mean or median for numerical variables, and mode for categorical variables)
- Fill the null values with the previous or next value in the column
- Fill the null values based on a more complex algorithm or model (note: we haven't covered this yet)

Implement your chosen strategy to handle the null values. You can use the `fillna()` function in pandas to fill null values or `dropna()` function to drop null values.

Verify that your strategy has successfully handled the null values. You can use the `isnull()` function again to check if there are still null values in the dataset.

Remember to document your process and explain your reasoning for choosing a particular strategy for handling null values.

After formatting data types, as a last step, convert all the numeric variables to integers.

In [14]:
print("Null values before cleaning:")
print(df.isnull().sum())

# Fill numerical nulls with median
numeric_columns = df.select_dtypes(include="number").columns

for column in numeric_columns:
    df[column] = df[column].fillna(df[column].median())

# Fill categorical nulls with mode
categorical_columns = df.select_dtypes(include="object").columns

for column in categorical_columns:
    df[column] = df[column].fillna(df[column].mode()[0])

print("\nNull values after cleaning:")
print(df.isnull().sum())

# Convert numeric variables to integers
for column in numeric_columns:
    df[column] = df[column].astype(int)

print(df.dtypes)

Null values before cleaning:
customer                     2937
state                        2937
gender                       3054
education                    2937
customer_lifetime_value      2940
income                       2937
monthly_premium_auto         2937
number_of_open_complaints    2937
policy_type                  2937
vehicle_class                2937
total_claim_amount           2937
dtype: int64

Null values after cleaning:
customer                     0
state                        0
gender                       0
education                    0
customer_lifetime_value      0
income                       0
monthly_premium_auto         0
number_of_open_complaints    0
policy_type                  0
vehicle_class                0
total_claim_amount           0
dtype: int64
customer                     object
state                        object
gender                       object
education                    object
customer_lifetime_value       int64
income                        int64
monthly_premium_auto          int64
number_of_open_complaints     int64
policy_type                  object
vehicle_class                object
total_claim_amount            int64
dtype: object

## Exercise 5: Dealing with duplicates

Use the `.duplicated()` method to identify any duplicate rows in the dataframe.

Decide on a strategy for handling the duplicates. Options include:
- Dropping all duplicate rows
- Keeping only the first occurrence of each duplicated row
- Keeping only the last occurrence of each duplicated row
- Dropping duplicates based on a subset of columns
- Dropping duplicates based on a specific column

Implement your chosen strategy using the `drop_duplicates()` function.

Verify that your strategy has successfully handled the duplicates by checking for duplicates again using `.duplicated()`.

Remember to document your process and explain your reasoning for choosing a particular strategy for handling duplicates.

Save the cleaned dataset to a new CSV file.

*Hint*: *after dropping duplicates, reset the index to ensure consistency*.

In [15]:
print("Duplicate rows before cleaning:")
print(df.duplicated().sum())

df = df.drop_duplicates()

df = df.reset_index(drop=True)

print("Duplicate rows after cleaning:")
print(df.duplicated().sum())

df.to_csv("cleaned_customer_data.csv", index=False)

Duplicate rows before cleaning:
2936
Duplicate rows after cleaning:
0

# Bonus: Challenge 2: creating functions on a separate `py` file

Put all the data cleaning and formatting steps into functions, and create a main function that performs all the cleaning and formatting.

Write these functions in separate .py file(s). By putting these steps into functions, we can make the code more modular and easier to maintain.

*Hint: autoreload module is a utility module in Python that allows you to automatically reload modules in the current session when changes are made to the source code. This can be useful in situations where you are actively developing code and want to see the effects of changes you make without having to constantly restart the Python interpreter or Jupyter Notebook kernel.*

In [16]:
%load_ext autoreload
%autoreload 2

from data_cleaning import clean_data

url = "https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv"

df_original = pd.read_csv(url)

df_clean = clean_data(df_original)

df_clean.head()

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

,customer,state,gender,education,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,policy_type,vehicle_class,total_claim_amount
0,RB50392,Washington,F,Master,588174,0,1000,0,Personal Auto,Four-Door Car,2
1,QZ44356,Arizona,F,Bachelor,697953,0,94,0,Personal Auto,Four-Door Car,1131
2,AI49188,Nevada,F,Bachelor,1288743,48767,108,0,Personal Auto,Two-Door Car,566
3,WW63253,California,M,Bachelor,764586,0,106,0,Corporate Auto,SUV,529
4,GA49547,Washington,M,High School or Below,536307,36357,68,0,Personal Auto,Four-Door Car,17

# Bonus: Challenge 3: Analyzing Clean and Formated Data

You have been tasked with analyzing the data to identify potential areas for improving customer retention and profitability. Your goal is to identify customers with a high policy claim amount and a low customer lifetime value.

In the Pandas Lab, we only looked at high policy claim amounts because we couldn't look into low customer lifetime values. If we had tried to work with that column, we wouldn't have been able to because customer lifetime value wasn't clean and in its proper format. So after cleaning and formatting the data, let's get some more interesting insights!

Instructions:

- Review the statistics again for total claim amount and customer lifetime value to gain an understanding of the data.
- To identify potential areas for improving customer retention and profitability, we want to focus on customers with a high policy claim amount and a low customer lifetime value. Consider customers with a high policy claim amount to be those in the top 25% of the total claim amount, and clients with a low customer lifetime value to be those in the bottom 25% of the customer lifetime value. Create a pandas DataFrame object that contains information about customers with a policy claim amount greater than the 75th percentile and a customer lifetime value in the bottom 25th percentile.
- Use DataFrame methods to calculate summary statistics about the high policy claim amount and low customer lifetime value data. To do so, select both columns of the dataframe simultaneously and pass it to the `.describe()` method. This will give you descriptive statistics, such as mean, median, standard deviation, minimum and maximum values for both columns at the same time, allowing you to compare and analyze their characteristics.

In [17]:
print(df_clean[["total_claim_amount", "customer_lifetime_value"]].describe())

claim_75 = df_clean["total_claim_amount"].quantile(0.75)
clv_25 = df_clean["customer_lifetime_value"].quantile(0.25)

high_claim_low_clv = df_clean.loc[
    (df_clean["total_claim_amount"] > claim_75) &
    (df_clean["customer_lifetime_value"] < clv_25)
]

print("\nFiltered customers:")
print(high_claim_low_clv)

print("\nSummary statistics:")
print(
    high_claim_low_clv[
        ["total_claim_amount", "customer_lifetime_value"]
    ].describe()
)

       total_claim_amount  customer_lifetime_value
count         1072.000000             1.072000e+03
mean           404.481343             7.929229e+05
std            292.909076             6.423980e+05
min              0.000000             2.004350e+05
25%            201.750000             4.054045e+05
50%            354.000000             5.881740e+05
75%            532.000000             8.937668e+05
max           2893.000000             5.816655e+06

Filtered customers:
     customer       state gender             education  \
17    OE15005  California      F               College
23    TZ98966      Nevada      F              Bachelor
26    US89481  California      F              Bachelor
38    CM61827      Oregon      F              Bachelor
42    IL19217  California      F              Bachelor
62    FG63582      Oregon      F              Bachelor
135   MS41162     Arizona      F  High School or Below
140   DS81757      Oregon      M               College
158   KA61892     Arizona      M               College
160   ND87334  California      M  High School or Below
170   TS19868  California      M               College
184   AB13432  California      M              Bachelor
204   FL34139  California      M  High School or Below
250   IA63417     Arizona      F  High School or Below
269   VZ51506     Arizona      F  High School or Below
279   OH60605      Oregon      F  High School or Below
304   RR77985      Oregon      F              Bachelor
388   JF36291  California      M               College
415   ZF84449      Oregon      F               College
448   NL93182      Nevada      M              Bachelor
450   WE68644      Oregon      F              Bachelor
467   AU96286      Oregon      F              Bachelor
486   FY51713     Arizona      F              Bachelor
500   XN11823      Nevada      F              Bachelor
502   PX17116      Nevada      M               College
565   XS12556  California      F               College
590   UK41984     Arizona      F                Doctor
593   ZK21724      Oregon      F  High School or Below
638   DM95829  California      M               College
645   JA41698      Nevada      M              Bachelor
669   ED50963  California      F  High School or Below
709   NZ15548      Oregon      M              Bachelor
788   TE13577      Oregon      F               College
853   TV25678  Washington      M               College
891   KJ87930  California      F              Bachelor
908   XM72420     Arizona      F  High School or Below
949   TD10493      Oregon      F  High School or Below
1019  OT52034  California      M              Bachelor
1022  UI73201  California      M               College
1068  GS98873     Arizona      F              Bachelor

      customer_lifetime_value  income  monthly_premium_auto  \
17                     394524   28855                   101
23                     245019       0                    73
26                     394637       0                   111
38                     309003       0                    90
42                     393900   60021                    99
62                     333976       0                    94
135                    402296       0                   117
140                    247012       0                    74
158                    387364   28142                   105
160                    228759       0                    63
170                    241313   27501                    63
184                    373583       0                   110
204                    368811       0                    63
250                    400151   19782                   108
269                    359531       0                   103
279                    365253   39679                    92
304                    288774       0                    80
388                    387364   28142                   105
415                    372672       0                   112
448                    254945       0                    78
450                    380392   20325                   100
467                    316765       0                    92
486                    357076   56168                    88
500                    376446   92600                    94
502                    362345       0                   111
565                    368309       0                   101
590                    383960       0                   112
593                    401654       0                   111
638                    252395   16244                    68
645                    309953       0                   102
669                    268886   32808                    68
709                    402381   41833                   103
788                    231973       0                    64
853                    354090       0                   101
891                    388650       0                   112
908                    391936   66676                    97
949                    289873       0                    96
1019                   386477   24204                    99
1022                   366737   62375                    92
1068                   323912   16061                    88

      number_of_open_complaints     policy_type  vehicle_class  \
17                            0   Personal Auto            SUV
23                            3  Corporate Auto  Four-Door Car
26                            0   Personal Auto  Four-Door Car
38                            0   Personal Auto   Two-Door Car
42                            0   Personal Auto  Four-Door Car
62                            0   Personal Auto   Two-Door Car
135                           0   Personal Auto            SUV
140                           0   Personal Auto   Two-Door Car
158                           0   Personal Auto         Luxury
160                           0  Corporate Auto   Two-Door Car
170                           0   Personal Auto  Four-Door Car
184                           0   Personal Auto            SUV
204                           3   Personal Auto  Four-Door Car
250                           0   Personal Auto   Two-Door Car
269                           0  Corporate Auto         Luxury
279                           0   Personal Auto   Two-Door Car
304                           0   Personal Auto  Four-Door Car
388                           0   Personal Auto         Luxury
415                           1    Special Auto         Luxury
448                           0  Corporate Auto  Four-Door Car
450                           0   Personal Auto         Luxury
467                           0  Corporate Auto  Four-Door Car
486                           0   Personal Auto  Four-Door Car
500                           0  Corporate Auto   Two-Door Car
502                           2  Corporate Auto            SUV
565                           0  Corporate Auto         Luxury
590                           2   Personal Auto            SUV
593                           0   Personal Auto            SUV
638                           0   Personal Auto   Two-Door Car
645                           5  Corporate Auto            SUV
669                           1   Personal Auto  Four-Door Car
709                           0   Personal Auto  Four-Door Car
788                           0   Personal Auto  Four-Door Car
853                           0   Personal Auto            SUV
891                           0  Corporate Auto            SUV
908                           0   Personal Auto  Four-Door Car
949                           4   Personal Auto  Four-Door Car
1019                          1   Personal Auto  Four-Door Car
1022                          0   Personal Auto   Two-Door Car
1068                          0   Personal Auto  Four-Door Car

      total_claim_amount
17                   647
23                   554
26                   799
38                   648
42                   882
62                   863
135                  975
140                  721
158                  701
160                  679
170                  542
184                  792
204                  669
250                  773
269                  741
279                  641
304                  676
388                  701
415                  806
448                  845
450                  668
467                  662
486                  614
500                  842
502                 1171
565                  564
590                  537
593                  799
638                  623
645                  862
669                  541
709                  643
788                  632
853                  727
891                 1185
908                  558
949                  691
1019                 707
1022                 618
1068                 633

Summary statistics:
       total_claim_amount  customer_lifetime_value
count           40.000000                40.000000
mean           723.300000            341577.425000
std            149.216449             56921.466178
min            537.000000            228759.000000
25%            632.750000            304220.500000
50%            685.000000            365995.000000
75%            799.000000            387364.000000
max           1185.000000            402381.000000